### ISSUE TITLE
Bundled polyfill loader not working in Firefox and Safari

### ISSUE THREAD

**Issue by aleksip** [mortenson/generator-twig-components-webpack#2]
Looks like the problem is similar to the one described [here](https://github.com/Polymer/polymer-cli/issues/905). Doesn't seem to be restricted to 'older browsers' as I've tested with Firefox Dev Edition and Safari 11.0.3.

~~Not sure if the polyfills should be bundled? If they are provided separately it means that clients that don't need them don't have to download them.~~ Right, it is just the loader that is bundled.

**Comment by mortenson** [comment]
@aleksip Nice catch - a temporary workaround is to change the `webcomponents-loader.js` to `webcomponents-lite.js` in webpack.config.js, then re-start your dev server.

It looks like ShadyCSS and ShadyDOM don't behave in exactly the way I would expect (style encapsulation doesn't account for parent-level `!important` styles), so I'm going to think on this more before making a change to the template.

**Comment by mortenson** [comment]
~~I'm also not seeing the `attributeChangedCallback` fired in Firefox, which is a huge dealbreaker. Could be something I'm doing, but I'm not sure.~~

Nevermind that, it's just editing attributes in the inspector that doesn't work. Phew!

**Comment by mortenson** [comment]
0.0.10 now uses `webcomponents-lite.js`, but also releases separate files for each Web Component which is probably preferable so you can choose what polyfills and Twig.js version you want.
